version: "3"

services:
  redis:
    image: redislabs/redistimeseries
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/data:/data
    command: --loadmodule /usr/lib/redis/modules/redistimeseries.so

  app-cron:
    build: ./app-cron
    container_name: letterboxd-stats-cron
    depends_on:
      - redis
    entrypoint: "/app/entrypoint.sh"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  app-client:
    build: ./app-client
    container_name: letterboxd-stats-client
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENV: prod
      PORT: 3000
      ASSETS_PATH: /root/assets/