version: "3"

services:
  redis:
    image: redislabs/redistimeseries
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/data:/data
    command: --loadmodule /usr/lib/redis/modules/redistimeseries.so

  app:
    build: .
    container_name: app
    depends_on:
      - redis
    entrypoint: "/app/entrypoint.sh"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379